import type { Course } from '../types';

export const COURSES: Course[] = [
    { id: 'ds', name: '資料結構', total: 69, color: 0, hours: 116 },
    { id: 'co', name: '計算機概論', total: 76, color: 1, hours: 136 },
    { id: 'net', name: '網際網路概論', total: 11, color: 2, hours: 13 },
    { id: 'db', name: '資料庫', total: 15, color: 3, hours: 17 },
    { id: 'mis', name: 'MIS', total: 28, color: 4, hours: 56 },
    { id: 'ai', name: 'AI', total: 26, color: 5, hours: 30 },
  ];

export const LESSONS: Record<string, string[]> = {
    'ds': ["資料結構部分-參考書籍","考題來源-數學類別","二項式係數","Permutation Print","效能分析","例題解析","Questions1","p.24","漸進式符號：Asymptotic notation","展開帶入法","例題解析","例題2","推疊與柱列","Stack permutations","例題解析","Infix轉Postfix之Algo","括號配對-例2","Queue的製作","Circular Array 作 Queue","利用Stack製作Queue","(八)樹的分支度","例題解析","B.T.之表示方法","例5","B.T. Traversal之應用","Tree Sorting","例題解析","Heap","Build a Heap","例題解析","Disjoint sets定義","FIND(i) with collapsing Rule","引線二元樹","例題解析","SMMH","Huffman Algo","Algo補充","AVL Tree Del.x","110中山資管資料結構","DELETE X IN A B TREE OF ORDER M","DELETE X IN A B TREE OF ORDER M","INSERT X IN THE RB TREE","RB-Tree","TABLE RESULT","OBST","BINOMIAL TREE","SEARCH AND SORT","Worst case","SELECTION SORT","例子","演算法版本-QUICK SORT","傳統方法","LSD RADIX SORT分析","Counting Sort","問題1","相鄰多元串列","演算法深度追蹤","判斷無向圖是否CONNECTED","MINIMUM SPANNING TREE (MST)","SOLLINS ALGORITHM","DIJKSTRAS ALGORITHM","求All pans of vertex 之 SPL","ARTICULATION POINT","HOW TO FIND THE ARTICULATION POINTS","OVERFLOW 處理方法","Ch2 Array 與 Ch4 Link list","三維、四維....N維陣列","例題3、Circular link list (環狀)","Generalized list 之 recursive operations"],
    'co': ["課程介紹","摩爾定律","運算元(operand)定址模式","cpu速度之評量方式與計算","Storage Hierarchy","時間，速率","數字系統","中正資工","補數","-3的二補數","Overflow (溢位)","一般型浮點數之值域","IEEE754特殊值以及值域","錯誤偵測碼","Hamming code","布林式子正規化表示方式","化簡SOP之步驟","UNIVERSAL GATES (COMPLETE GATE)","XOR GATE AND XNOR GATE 特性","例題解析","正反器","作業系統","SYSTEM TYPES","第四段","Real-Time system (即時系統)","INTERRUPTED I/O","DMA (Direct Memory Access)","SYSTEM CALLS","111中山資管計概","作業系統部分CH4","Process之STD","I/O-bound and CPU-bound process","Non-Preemptive 與 Preemptive 排班","PRIORITY SCHEDULING","SCHEDULABLE","Child process佔用的Address space","例1","破除No Preemption條件","STEPS OF BANKER ALGORITHM","Contiguous Memory Allocation","Translate a logical address generated by the CPU to a physical addres","A two-level page-table scheme","虛擬記憶體","LRU-Approximation Page Replacement","Working Model 工作模型","Seek Time","Linked Allocation","Improvement of Reliability via Redundancy","outline","彼得森解法","程式語言-系統程式","程式語言-結構化程式","程式語言-指標變數 P17","程式語言-雙重指標","程式語言-p.36","程式語言-C++","程式語言-Call by reference 傳參考","程式語言-Person","程式語言-例外處理的機制","程式語言-例題解析 P36","程式語言-p.55","程式語言-ex12","資結-CH1-AlgorithmSpecification","資結-對數系列","資結-上課筆記","資結-四.比較表-上課筆記","資結-四infix轉postfix.piefix","資結-CircularLinkList","資結-CompleteBT上課筆記","資結-Heap堆積上課筆記","資結-定理-上課筆記","資結-四DeleteX上課筆記","資結-Sorting上課筆記","資結-Morg sort-合併排序","資結-Adjacency Lists表示-相鄰串列","資結-AlgoFloyd-warshall上課筆記"],
    'net': ["簡介","網路層","數據機","數據通訊方式","終端節點隱藏問題","藍芽技術","子網路","IPV6","傳輸協定","網路管理","攻擊方式"],
    'db': ["第一篇：資料庫系統概念","資料架構的發展","(1) 資料處理模式的演進","(三)、關聯式資料庫","(4) 複合鍵 / 組合鍵","關聯式代數的特性","強實體 / 實體類型","自然語言句型","實體關聯圖轉換成關聯表綱要","正規化的概念","第三階正規化型式","正規化練習","查詢紀錄","where子句的算數運算子","NoSQL定義與歷史"],
    'mis': ["開課","資訊系統","p.15","p.27","Class3-1","Class3-2","寫申論題的步驟","例題解析","p.71","p.146","p.90","3H:2L","採用IT主要的目的之一","p.234","p.268","p.156","第五章 複習 P176","私有產業網路 P16","p.27","p.115","考研關鍵要素","p.79","第九章","p.223","CH11","p.138","CH12 資訊系統投資效益","何謂長尾理論與網路外部性"],
    'ai': ["人工智慧基礎定義","人工智慧主要演算法","人工智慧衡量方法","(五)循環神經網路RNN","2.調整參數","2.提供範例","(3)提升法","5.文本分析","A.協同過濾演算法","2.行動設備","(2)文件報表","人工智慧","(三)產業應用","(4)防止金融犯罪","九、風險與威脅","一、AI導入主要流程","2.策略缺口分析","8.高階主管支持","目錄","AH","密碼保護","安全委外","邊界網路","(二)無線網路與企業內部的安全機制","(四)題型演練","交通大學-資管所34"],
  };

export const LESSON_DURATIONS: Record<string, number[]> = {
    'ds': [6536,6128,7559,2956,7931,5907,7050,3299,6787,5493,6720,6180,7532,3559,7051,6839,6300,4486,6849,4603,7543,6017,7553,3034,6982,6359,6922,3401,7257,6322,6094,3873,7248,5711,7262,3916,7926,6188,6347,3280,6722,7064,7060,2849,6982,5815,6991,3348,7817,6415,9215,7495,3346,7917,7202,6332,3629,7370,6587,7466,5786,7474,1815,7007,5197,3785,7139,5311,7696],
    'co': [6274,4225,8922,3104,7576,4453,7685,3436,7506,3739,7859,3450,7175,3788,7415,3930,8074,3382,7685,3402,7780,3161,7505,3602,7414,3753,7499,3683,7951,3324,7449,3988,7527,3620,7817,3718,7804,3480,7923,3755,7815,3463,7476,3496,7493,3693,7864,3249,7857,3684,5923,3937,5466,5328,5909,5256,5125,4248,5750,3900,5416,4510,13707,11270,14229,10703,14045,10381,14812,10940,13568,11837,14626,10835,14777,9164],
    'net': [5420,3097,2641,2469,5715,4471,5278,2495,4991,4337,5375],
    'db': [5548,4753,4061,2912,2731,5673,4800,2645,2512,3773,3702,3900,3406,5801,4673],
    'mis': [6435,5568,6764,5451,6956,4450,6926,5248,6915,4173,7099,4961,6765,5700,6686,5412,7042,5061,6792,1977,6354,5314,5633,6064,6163,4511,6243,3795],
    'ai': [5065,4825,4313,2599,2601,2575,5280,4344,3384,2550,3237,2886,5561,4287,2531,3123,3565,2850,5201,4661,3777,3485,4134,3901,3414,2341],
  };
